FROM python:3.10

WORKDIR /producer

COPY producer.txt .

RUN pip install --no-cache-dir -r producer.txt

COPY VN_Index_Historical_Data.csv .

COPY file2kafka.py .

COPY .kafka.env .

ENTRYPOINT ["python", "file2kafka.py"]